CaritasDeutschland/caritas-onlineBeratung-messageService

.github/workflows/release.yml, CHANGELOG.md, package-lock.json, package.json
=> Release 2020 07 30

CHANGELOG.md, package-lock.json, package.json
=> Release 2020 10 13

src/main/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacade.java
=> fix: check boolean against null

pom.xml, services/userservice.yaml, src/main/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacade.java, src/main/java/de/caritas/cob/messageservice/api/service/LiveEventNotificationService.java, src/main/java/de/caritas/cob/messageservice/config/apiclient/LiveProxyApiClientConfig.java, src/main/resources/application-testing.properties, src/main/resources/application.properties, src/test/java/de/caritas/cob/messageservice/api/config/apiclient/LiveProxyApiClientConfigIT.java, src/test/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacadeTest.java, src/test/java/de/caritas/cob/messageservice/api/service/LiveEventNotificationServiceTest.java
=> Feature live message notification

api/messageservice.yaml, pom.xml, src/main/java/de/caritas/cob/messageservice/api/controller/MessageController.java, src/main/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacade.java, src/main/java/de/caritas/cob/messageservice/api/model/draftmessage/SavedDraftType.java, src/main/java/de/caritas/cob/messageservice/api/model/draftmessage/entity/DraftMessage.java, src/main/java/de/caritas/cob/messageservice/api/model/entity/DraftMessage.java, src/main/java/de/caritas/cob/messageservice/api/repository/DraftMessageRepository.java, src/main/java/de/caritas/cob/messageservice/api/service/DraftMessageService.java, src/main/java/de/caritas/cob/messageservice/config/SecurityConfig.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties, src/main/resources/application-staging.properties, src/main/resources/application-testing.properties, src/main/resources/application.properties, src/main/resources/db/changelog/changeset/0001_initsql/initSql.xml, src/main/resources/db/changelog/changeset/0001_initsql/initTables.sql, src/main/resources/db/changelog/changeset/0001_initsql/initTrigger.sql, src/main/resources/db/changelog/messageservice-dev-master.xml, src/main/resources/db/changelog/messageservice-local-master.xml, src/main/resources/db/changelog/messageservice-prod-master.xml, src/main/resources/db/changelog/messageservice-staging-master.xml, src/main/resources/db/changelog/messageservice-testing-master.xml, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerTestIT.java, src/test/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacadeTest.java, src/test/java/de/caritas/cob/messageservice/api/service/DraftMessageServiceTest.java
- uses a new database for messageservice
=> Feature save draft messages

src/main/java/de/caritas/cob/messageservice/api/controller/MessageController.java, src/main/java/de/caritas/cob/messageservice/api/service/DraftMessageService.java, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerTestIT.java, src/test/java/de/caritas/cob/messageservice/api/service/DraftMessageServiceTest.java
=> Feature load saved draft messages

.github/workflows/release.yml
=> feat: restrict release action to relase starting branches

pom.xml, src/main/java/de/caritas/cob/messageservice/config/SecurityConfig.java, src/main/resources/application-testing.properties, src/main/resources/application.properties, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerTestIT.java, src/test/java/de/caritas/cob/messageservice/api/helper/UserHelperTest.java, src/test/java/de/caritas/cob/messageservice/testhelper/TestConstants.java
=> feat: update spring boot and dependencies

src/main/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacade.java, src/main/resources/application-testing.properties, src/test/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacadeTest.java
=> feat: prevent live event trigger for rocket chat system user

pom.xml
- this requires the update of keycloak to 11.0.2
=> feat: update keycloak to 11.0.2

api/messageservice.yaml, src/main/resources/application.properties
=> feat: add api authorization hint and rc systemuser id in properties

pom.xml, src/main/java/de/caritas/cob/messageservice/api/service/DraftMessageService.java, src/main/resources/application-testing.properties, src/test/java/de/caritas/cob/messageservice/api/config/apiclient/LiveProxyApiClientConfigIT.java, src/test/java/de/caritas/cob/messageservice/api/service/DraftMessageServiceIT.java, src/test/resources/database/MessageDatabase.sql
Fixes #
a concurrency issue when a draft message delete and save call are executed at same time
=> fix: concurrency issue when save and delete a draft message in parallel

api/messageservice.yaml, src/main/java/de/caritas/cob/messageservice/api/controller/MessageController.java, src/main/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacade.java, src/main/java/de/caritas/cob/messageservice/api/service/RocketChatService.java, src/main/java/de/caritas/cob/messageservice/config/SecurityConfig.java, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerAuthorizationTestIT.java, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerTestIT.java, src/test/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacadeTest.java, src/test/java/de/caritas/cob/messageservice/api/service/RocketChatServiceTest.java
Added call to post a further steps message to a Rocket.Chat group
POST /messages/furthersteps/new
Header:
rcGroupId (required)
=> Feature add further steps to alias

src/main/java/de/caritas/cob/messageservice/config/SecurityConfig.java, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerAuthorizationTestIT.java
Changed endpoint authority to user default
=> chore: changed endpoint authority to user default

src/main/java/de/caritas/cob/messageservice/config/SecurityConfig.java, src/main/java/de/caritas/cob/messageservice/filter/StatelessCsrfFilter.java, src/main/resources/application.properties, src/test/java/de/caritas/cob/messageservice/filter/StatelessCsrfFilterTest.java
=> feat: added csrf whitelist property

CHANGELOG.md, package-lock.json, package.json
=> release-2021-03-23

CHANGELOG.md, package-lock.json, package.json
=> release-2021-03-23_v2

api/messageservice.yaml, src/main/java/de/caritas/cob/messageservice/api/controller/MessageController.java, src/main/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacade.java, src/main/java/de/caritas/cob/messageservice/config/SecurityConfig.java, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerAuthorizationTestIT.java, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerTestIT.java, src/test/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacadeTest.java
Adapted further steps message call to post an alias only message depending on the message type.
=> Feature adapt message type call

src/main/java/de/caritas/cob/messageservice/api/service/RocketChatService.java
=> feat: extend logging for better analysis

api/messageservice.yaml, src/main/java/de/caritas/cob/messageservice/config/SecurityConfig.java, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerAuthorizationTestIT.java
=> feat: added new alias message type

src/main/java/de/caritas/cob/messageservice/config/SecurityConfig.java, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerAuthorizationTestIT.java
=> feat: add required authorities for alias only message

src/main/java/de/caritas/cob/messageservice/config/SecurityConfig.java, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerAuthorizationTestIT.java
Reverts CaritasDeutschland/caritas-onlineBeratung-messageService#56
=> Revert "feat: add required authorities for alias only message"

pom.xml
=> feat: adapt new keycloak version

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 2.4.0

readme.md
=> docs: added service description

src/main/java/de/caritas/cob/messageservice/api/service/RocketChatService.java
Reverts CaritasDeutschland/caritas-onlineBeratung-messageService#72
=> Revert "test: log message group call"

api/messageservice.yaml, src/main/java/de/caritas/cob/messageservice/api/helper/JSONHelper.java, src/main/java/de/caritas/cob/messageservice/api/model/jsondeserializer/AliasJsonDeserializer.java, src/main/java/de/caritas/cob/messageservice/api/service/RocketChatService.java, src/test/java/de/caritas/cob/messageservice/api/helper/JSONHelperTests.java
Reverts CaritasDeutschland/caritas-onlineBeratung-messageService#71
=> Revert "feat: identify user-muted message"

api/messageservice.yaml, src/main/java/de/caritas/cob/messageservice/api/controller/MessageController.java, src/main/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacade.java, src/main/java/de/caritas/cob/messageservice/api/service/MessageMapper.java, src/main/java/de/caritas/cob/messageservice/api/service/RocketChatService.java, src/test/java/de/caritas/cob/messageservice/api/controller/MessageControllerE2EIT.java, src/test/java/de/caritas/cob/messageservice/api/facade/PostGroupMessageFacadeTest.java, src/test/java/de/caritas/cob/messageservice/testhelper/TestConstants.java
* to be able to check, if the message is successfully sent as e2ee
=> feat: introduce response type for sending messages
